# Generated by Django 4.2.20 on 2025-04-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteOrderFormRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('website_type', models.CharField(choices=[('Personal', 'شخصی'), ('For a business', 'کاری'), ('For a company', 'شرکتی'), ('Online Shop', 'فروشگاهی')], default='Choose an option', max_length=20)),
                ('design_type', models.CharField(choices=[('Wordpress', 'وردپرسی'), ('Coding', 'کدنویسی')], default='Choose an option', max_length=20)),
                ('min_price', models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=1000000000, max_digits=10)),
                ('min_time', models.IntegerField(default=2)),
                ('max_time', models.IntegerField(default=100)),
            ],
        ),
    ]
