# Generated by Django 4.2.20 on 2025-04-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_websiteorderformrequest_design_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteorderformrequest',
            name='design_type',
            field=models.CharField(choices=[('', 'Wordpress'), ('', 'Coding')], default='Choose an option', max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteorderformrequest',
            name='website_type',
            field=models.CharField(choices=[('', 'Personal'), ('', 'For a business'), ('', 'For a company'), ('', 'Online Shop')], default='Choose an option', max_length=20),
        ),
    ]
