# Generated by Django 4.2.20 on 2025-04-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_websiteorderformrequest_design_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteorderformrequest',
            old_name='max_time',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='websiteorderformrequest',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='websiteorderformrequest',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='websiteorderformrequest',
            name='min_time',
        ),
        migrations.AddField(
            model_name='websiteorderformrequest',
            name='time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='websiteorderformrequest',
            name='design_type',
            field=models.CharField(choices=[('WordPress', 'WordPress'), ('Coding', 'Coding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='websiteorderformrequest',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='websiteorderformrequest',
            name='website_type',
            field=models.CharField(choices=[('E-commerce', 'E-commerce'), ('Portfolio', 'Portfolio'), ('Blog', 'Blog'), ('Corporate', 'Corporate')], max_length=100),
        ),
    ]
