# Generated by Django 4.2.20 on 2025-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_max_time_websiteorderformrequest_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteorderformrequest',
            name='time',
        ),
        migrations.AddField(
            model_name='websiteorderformrequest',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=13),
            preserve_default=False,
        ),
    ]
