# Generated by Django 4.2.20 on 2025-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_websiteorderformrequest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteorderformrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
