# Generated by Django 4.2.20 on 2025-04-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_websiteorderformrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteorderformrequest',
            name='phone_number',
        ),
    ]
