# Generated by Django 4.2.20 on 2025-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_websiteorderformrequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
