# Generated by Django 4.2.20 on 2025-04-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_contactrequest_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteorderformrequest',
            name='website_type',
        ),
    ]
